### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/infra.platform_configuration#2]
The other infra collections are named for their function. However this collection is named platform

If this is not meant to br a big bucket to merge the infra collections should we rename it?

What is the official product name for gateway?, or how should we ne it?

**Comment by Tompage1994** [comment]
I'd opt for infra.gateway_configuration, but it seems the dependency is ansible.gateway_configuration which doesn't really match the naming standards.

I'd like to hope that collection is going to be renamed to ansible.gateway then it definitely makes sense for this to be infra.gateway_configuration

**Comment by sean-m-sullivan** [comment]
We have roles now and a plan closing this.
